---
Name: rmsroutes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    property/$Action/$ID/$Name: RMSController
    rmssearch/$Action/$ID/$Name: RMSController
    rets/$$Action/$ID/$Name: RETS_Controller
---
Name: maintenance
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    maintenance/$Action/$ID/$Name: RMSMaintenance
